name: goodloc-workflow-prod-CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
          no-cache: true

      - name: Scan Docker image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@v0.11.1
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
          format: 'table'
          output: trivy_report.txt  # Sauvegarde le rapport dans un fichier
          ignore-unfixed: true
          vuln-type: 'os,library'
        continue-on-error: true

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
          no-cache: true

      - name: Send email notification
        if: failure()  # Exécute cette étape seulement si Trivy a trouvé des vulnérabilités
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Adresse SMTP de gmail
          server_port: 587  # Port SMTP
          username: ${{ secrets.EMAIL_USERNAME }}  # Nom d'utilisateur pour l'envoi
          password: ${{ secrets.EMAIL_PASSWORD }}  # Mot de passe pour l'envoi
          subject: "Vulnerabilities found in Docker image"
          body: "Trivy scan has detected vulnerabilities in the Docker image. Please review the attached report."
          to: "romgacode@gmail.com"  # Adresse email de destination
          from: "noreply@trivytest.com"  # Adresse email de l'expéditeur
          attachments: trivy_report.txt  # Attache le rapport Trivy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsagoodlocbck
          chmod 600 ~/.ssh/id_rsagoodlocbck
          ssh-keyscan -H 185.97.144.183 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH connectivity
        run: |
          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "echo SSH connection successful"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose file to server
        run: |
          scp -i ~/.ssh/id_rsagoodlocbck -o StrictHostKeyChecking=no docker-compose.prod.yml root@185.97.144.183:/GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml
          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "ls -l /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH login to server and deploy
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 185.97.144.183
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -f /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml ]; then
              echo "File /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml found!"
              cd /GoodLoc24_backDev/docker-compose.prod.yml
              docker --version
              docker-compose --version
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
              docker-compose -f docker-compose.prod.yml down || true
              docker-compose -f docker-compose.prod.yml up -d
            else
              echo "File /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml not found!"
              exit 1
            fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
