
name: goodloc-workflow-dev-CI/CD

on:
  push:
    branches:
      - goodloc_dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goodloc-dev:latest
          no-cache: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsagoodlocbck
          chmod 600 ~/.ssh/id_rsagoodlocbck
          ssh-keyscan -H 185.97.144.183 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH connectivity
        run: |
          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "echo SSH connection successful"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose file to server
        run: |
          scp -i ~/.ssh/id_rsagoodlocbck -o StrictHostKeyChecking=no docker-compose.dev.yml root@185.97.144.183:/GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml
          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "ls -l /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH login to server and deploy
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 185.97.144.183
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -f /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml ]; then
              echo "File /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml found!"
              cd /GoodLoc24_backDev/docker-compose.dev.yml
              docker --version
              docker-compose --version
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goodloc-dev:latest
              docker-compose -f docker-compose.dev.yml down || true
              docker-compose -f docker-compose.dev.yml up -d
            else
              echo "File /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml not found!"
              exit 1
            fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}