name: goodloc24-CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rmag17/goodloc24back:latest
        login-username: ${{ secrets.DOCKERHUB_USERNAME }}
        login-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        builder: '--platform=linux/amd64'
        cache-from: 'rmag17/goodloc24back:latest'
        cache-to: 'rmag17/goodloc24back-cache'
        labels: 'version=1.0.0,app=goodloc24,builder=github-actions'
        args:
          JAR_FILE: target/goodloc24-0.0.1-SNAPSHOT.jar


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH login to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker pull rmag17/goodloc24back:latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 8080:8080 --name app rmag17/goodloc24back:latest
